server/urls.py
"""

Transportation Portal URL Configuration

"""

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework_social_oauth2.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('', include('transportation.urls'))

]

transportation/urls.py
from django.urls import include, path

from transportation import views, models


urlpatterns = [
    path('auth/', include('rest_framework_social_oauth2.urls')),
    path('', include('social_django.urls', namespace='social')),

    path('sign-in/', views.LoginView.as_view(), name='sign-in'),
    path('sign-out/', views.sign_out, name='sign-out'),

    path('orgs/', views.OrganizationsView.as_view(), name='org-list'),
    path('orgs/report', views.run_org_report, name='org-report'),
    path('orgs/new', views.CreateOrganizationView.as_view(), name='new-org'),
    path('orgs/delete', views.delete_orgs, name='delete-orgs'),
    path('orgs/<int:pk>/', views.OrganizationDetailView.as_view(), name='org-detail'),
    path('orgs/<int:pk>/edit', views.UpdateOrganizationView.as_view(), name='edit-org'),
    path('orgs/<int:pk>/delete', views.delete_org, name='delete-org'),
    path('orgs/<int:org_pk>/budgets', views.BudgetsView.as_view(), name='budget-list'),
    path('orgs/<int:org_pk>/budgets/new', views.CreateBudgetView.as_view(), name='new-budget'),
    path('orgs/<int:org_pk>/budgets/delete', views.delete_budgets, name='delete-budgets'),
    path('orgs/<int:org_pk>/budgets/<int:pk>/', views.BudgetDetailView.as_view(), name='budget-detail'),
    path('orgs/<int:org_pk>/budgets/<int:pk>/edit',
         views.UpdateBudgetView.as_view(), name='edit-budget'),
    path('orgs/<int:org_pk>/budgets/<int:pk>/delete', views.delete_budget, name='delete-budget'),
    path('orgs/<int:org_pk>/departments', views.DepartmentsView.as_view(), name='department-list'),
    path('orgs/<int:org_pk>/departments/new',
         views.CreateDepartmentView.as_view(), name='new-department'),
    path('orgs/<int:org_pk>/departments/delete', views.delete_departments, name='delete-departments'),
    path('orgs/<int:org_pk>/departments/<int:pk>/',
         views.DepartmentDetailView.as_view(), name='department-detail'),
    path('orgs/<int:org_pk>/departments/<int:pk>/edit',
         views.UpdateDepartmentView.as_view(), name='edit-department'),
    path('orgs/<int:org_pk>/departments/<int:pk>/delete',
         views.delete_department, name='delete-department'),

    path('drivers/', views.DriversView.as_view(), name='driver-list'),
    path('drivers/report', views.run_driver_report, name='driver-report'),
    path('drivers/new', views.CreateDriverView.as_view(), name='new-driver'),
    path('drivers/delete', views.delete_drivers, name='delete-drivers'),
    path('drivers/<int:pk>/', views.DriverDetailView.as_view(), name='driver-detail'),
    path('drivers/<int:pk>/edit', views.UpdateDriverView.as_view(), name='edit-driver'),
    path('drivers/<int:pk>/delete', views.delete_driver, name='delete-driver'),
    path('drivers/<int:pk>/deactivate', views.deactivate_driver, name='deactivate-driver'),
    path('drivers/<int:pk>/reactivate', views.reactivate_driver, name='reactivate-driver'),

    path('vehicles/', views.VehiclesView.as_view(), name='vehicle-list'),
    path('vehicles/report', views.run_vehicle_report, name='vehicle-report'),
    path('vehicles/new', views.CreateVehicleView.as_view(), name='new-vehicle'),
    path('vehicles/<int:pk>/edit', views.UpdateVehicleView.as_view(), name='edit-vehicle'),
    path('vehicles/<int:pk>/delete', views.delete_vehicle, name='delete-vehicle'),
    path('vehicles/<int:vehicle_pk>/', views.VehicleDetailView.as_view(), name='vehicle-detail'),
    path('vehicles/<int:vehicle_pk>/maintenance/new',
         views.CreateVehicleMaintenanceView.as_view(), name='new-vehicle-maintenance'),
    path('vehicles/<int:vehicle_pk>/maintenance/<int:pk>/edit',
         views.UpdateVehicleMaintenanceView.as_view(), name='edit-vehicle-maintenance'),
    path('vehicles/<int:vehicle_pk>/maintenance/<int:pk>/delete',
         views.delete_vehicle_maintenance, name='delete-vehicle-maintenance'),

    path('requests/', views.TripRequestsView.as_view(), name='request-list'),
    path('requests/report', views.run_triprequest_report, name='request-report'),
    path('requests/print/labels', views.print_labels, name='print-labels'),
    path('requests/print/tickets', views.print_tickets, name='print-tickets'),
    path('requests/new', views.CreateTripRequestView.as_view(), name='new-request'),
    path('requests/<int:pk>/assign-self', views.assign_request_moderator, name='request-assign-self'),
    path('requests/<int:pk>/', views.TripRequestDetailView.as_view(), name='request-detail'),
    path('requests/<int:pk>/update', views.update_request, name='request-update'),
    path('requests/<int:pk>/pending', views.pending_request, name='request-pending'),
    path('requests/<int:pk>/edit', views.UpdateTripRequestView.as_view(), name='edit-request'),
    path('requests/<int:pk>/delete', views.delete_trip_request, name='delete-request'),
    path('requests/<int:pk>/approve', views.approve_request, name='approve-request'),
    path('requests/<int:pk>/deny', views.deny_request, name='deny-request'),
    path('requests/<int:pk>/cancel', views.cancel_trip_request, name='cancel-request'),
    path('requests/<int:pk>/return-vehicle', views.return_request_vehicle, name='return-request-vehicle'),
    path('requests/<int:pk>/finalize', views.finalize_request, name='finalize-request'),

    path('ajax/load-departments', views.load_departments, name='load-departments'),
    path('ajax/load-budgets', views.load_budgets, name='load-budgets'),
    path('ajax/load-drivers', views.load_drivers, name='query-drivers'),

    path('', views.HomeView.as_view(), name='home')
]

transportation/models/managers.py
from django.db import models


class DriverManager(models.Manager):
    pass

transportation/models/orgs.py
from django.db import models


class Organization(models.Model):
    id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=50)

    def __str__(self): return self.name


class Department(models.Model):
    num = models.CharField(
        primary_key=True,
        max_length=20,
        verbose_name='Department #'
    )

    org = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name='departments',
        verbose_name='Organization'
    )

    name = models.CharField(
        max_length=50,
        verbose_name='Name'
    )

    def __str__(self): return self.name


class Budget(models.Model):
    num = models.CharField(
        primary_key=True,
        max_length=20,
        verbose_name='Budget #'
    )

    org = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        verbose_name='Organization',
        related_name='budgets'
    )

    name = models.CharField(
        max_length=50,
        verbose_name='Name'
    )

    def __str__(self): return self.name

transportation/models/settings.py
from django.db import models


class Setting(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.CharField(max_length=255, unique=True)
    value = models.TextField()

transportation/models/triprequests.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from phone_field import PhoneField

from transportation import validators


class TripRequest(models.Model):
    STATUS_NONE = 0
    STATUS_PENDING = 1
    STATUS_APPROVED = 2
    STATUS_DENIED = 3
    STATUS_COMPLETED = 4
    STATUS_CANCELLED = 5
    STATUS_OTHER = 6
    STATUS_RETURNED = 7
    STATUS_CHOICES = (
        (STATUS_NONE,           'None'),
        (STATUS_PENDING,        'Pending'),
        (STATUS_APPROVED,       'Approved'),
        (STATUS_DENIED,         'Denied'),
        (STATUS_COMPLETED,      'Completed'),
        (STATUS_CANCELLED,      'Cancelled'),
        (STATUS_OTHER,          'Other'),
        (STATUS_RETURNED,       'Returned'),
    )

    TYPE_UNKNOWN = 0
    TYPE_CAR = 1
    TYPE_PVAN = 2
    TYPE_CVAN = 3
    TYPE_BUS = 4
    TYPE_CBUS = 5
    TYPE_RBUS = 6
    TYPE_TRUCK = 7
    TYPE_NOCDL_BUS = 8
    TYPE_GOLFCART = 9
    TYPE_CHOICES = (
        (TYPE_UNKNOWN,   'Unknown'),
        (TYPE_CAR,       'Car'),
        (TYPE_PVAN,      'Passenger Van'),
        (TYPE_CVAN,      'Cargo Van'),
        (TYPE_BUS,       'Bus'),
        (TYPE_CBUS,      'Coach Bus'),
        (TYPE_RBUS,      'Road Bus'),
        (TYPE_TRUCK,     'Truck'),
        (TYPE_NOCDL_BUS, 'Non-CDL Bus'),
        (TYPE_GOLFCART,  'Golf Cart')
    )

    KEY_NONE = 0
    KEY_RED = 1
    KEY_BLUE = 2
    KEY_GREEN = 3
    KEY_YELLOW = 4
    KEY_WHITE = 5
    KEY_CHOICES = (
        (KEY_NONE,   'None'),
        (KEY_RED,    'Red'),
        (KEY_BLUE,   'Blue'),
        (KEY_GREEN,  'Green'),
        (KEY_YELLOW, 'Yellow'),
        (KEY_WHITE,  'White')
    )

    id = models.AutoField(primary_key=True)

    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        verbose_name='Status'
    )

    org = models.ForeignKey(
        'Organization',
        on_delete=models.PROTECT,
        verbose_name='Organization'
    )

    submitted = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Submitted'
    )

    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')

    manager = models.ForeignKey(
        get_user_model(),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        related_name='manager',
        verbose_name='Manager'
    )

    signed_off = models.DateField(
        null=True, blank=True,
        verbose_name='Signed Off On'
    )

    requestor = models.ForeignKey(
        get_user_model(),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        related_name='requestor',
        verbose_name='Requestor'
    )

    contact_fn = models.CharField(
        max_length=32,
        verbose_name='First Name'
    )

    contact_ln = models.CharField(
        max_length=32,
        verbose_name='Last Name'
    )

    contact_phone = PhoneField(
        verbose_name='Phone #'
    )

    contact_email = models.EmailField(
        verbose_name='Email Address'
    )

    department = models.ForeignKey(
        'Department',
        on_delete=models.PROTECT,
        verbose_name='Department'
    )

    budget = models.ForeignKey(
        'Budget',
        on_delete=models.PROTECT,
        verbose_name='Budget'
    )

    requested_driver = models.CharField(
        max_length=255,
        null=True, blank=True
    )

    driver = models.ForeignKey(
        'Driver',
        null=True, blank=True,
        on_delete=models.PROTECT,
        related_name='trips',
        verbose_name='Driver'
    )

    vehicle_type = models.PositiveSmallIntegerField(
        default=TYPE_UNKNOWN,
        choices=TYPE_CHOICES,
        verbose_name='Vehicle Type'
    )

    vehicle = models.ForeignKey(
        'Vehicle',
        null=True, blank=True,
        on_delete=models.PROTECT,
        related_name='trips',
        verbose_name='Vehicle'
    )

    party_count = models.PositiveSmallIntegerField(
        default=1,
        verbose_name='Party Count'
    )

    depart_est = models.DateTimeField(
        verbose_name='Depart Time (Estimate)'
    )

    return_est = models.DateTimeField(
        verbose_name='Return Time (Estimate)'
    )

    depart_act = models.DateTimeField(
        null=True, blank=True,
        verbose_name='Depart Time (Actual)'
    )

    return_act = models.DateTimeField(
        null=True, blank=True,
        verbose_name='Return Time (Actual)'
    )

    destination = models.CharField(
        max_length=255,
        verbose_name='Destination'
    )

    purpose = models.TextField(
        verbose_name='Purpose'
    )

    trailer = models.BooleanField(
        default=False,
        verbose_name='Trailer'
    )

    agreement_accepted = models.BooleanField(
        default=False,
        verbose_name='Accept Agreement'
    )

    mileage_est = models.PositiveIntegerField(
        verbose_name='Mileage (Estimate)'
    )

    mileage_act = models.PositiveIntegerField(
        null=True, blank=True,
        verbose_name='Mileage (Actual)'
    )

    card_num = models.CharField(
        null=True, blank=True,
        max_length=32,
        verbose_name='Card #'
    )

    key_color = models.PositiveSmallIntegerField(
        verbose_name='Key Tag Color',
        choices=KEY_CHOICES,
        default=KEY_NONE
    )

    fuel_cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0.00,
        null=True, blank=True,
        verbose_name='Fuel Cost'
    )

    is_vehicle_clean = models.BooleanField(
        default=False,
        verbose_name='Vehicle Cleanliness'
    )

    is_vehicle_parked_proper = models.BooleanField(
        default=False,
        verbose_name='Vehicle Parked Correctly'
    )

    vehicle_problems = models.CharField(
        max_length=256,
        null=True, blank=True
    )

    @property
    def is_modifiable(self):
        return self.status != 3 and self.status != 4 and self.status != 5

    @property
    def last_updator(self):
        last_activity = TripRequestActivity.objects.filter(request=self).latest()
        return last_activity.user

    @property
    def fuel_cost_display(self):
        return f'${self.fuel_cost}'

    @property
    def org_department(self):
        return f'{self.org} - {self.department}'

    @property
    def title(self):
        return f"{self.requestor_fullname}'s Trip Request"

    @property
    def daterange(self):
        return f"{self.depart_est.strftime('%b %d, %Y')} - {self.return_est.strftime('%b %d, %Y')}"

    @property
    def manager_fullname(self):
        if self.manager is None:
            return f'{self.manager}'
        return f'{self.manager.first_name} {self.manager.last_name}'

    @property
    def requestor_fullname(self):
        if self.requestor is None:
            return f'{self.contact_fullname}'
        return f"{self.requestor.first_name} {self.requestor.last_name}"

    @property
    def driver_fullname(self):
        if self.driver is None:
            return None
        return f'{self.driver.first_name} {self.driver.last_name}'

    @property
    def contact_fullname(self):
        return f'{self.contact_fn} {self.contact_ln}'

    @property
    def is_pending(self):
        return self.status == TripRequest.STATUS_PENDING

    @property
    def is_approved(self):
        return self.status == TripRequest.STATUS_APPROVED

    @property
    def is_denied(self):
        return self.status == TripRequest.STATUS_DENIED

    @property
    def is_completed(self):
        return self.status == TripRequest.STATUS_COMPLETED

    @property
    def is_cancelled(self):
        return self.status == TripRequest.STATUS_CANCELLED

    @property
    def is_returned(self):
        return self.status == TripRequest.STATUS_RETURNED

    @property
    def is_valid(self):
        return self.manager is not None and \
            self.driver is not None and \
            self.vehicle is not None and \
            self.card_num is not None
        # not self.is_departure_estimate_late and
        # not self.is_return_estimate_late and

    @property
    def is_departure_estimate_late(self):
        if self.is_pending:
            return self.depart_est < timezone.now()
        else:
            return False

    @property
    def is_return_estimate_late(self):
        if self.is_pending:
            return self.return_est < timezone.now()
        else:
            return False

    @property
    def can_finalize(self):
        return self.is_returned  # self.depart_act is not None and self.return_act is not None and self.is_returned

    @property
    def can_return(self):
        return True  # self.depart_act is not None and self.return_act is not None

    @property
    def is_missing_requirements(self):
        return self.manager is None or self.vehicle is None or self.driver is None or self.card_num is None or self.key_color is None

    @property
    def vehicle_type_display(self):
        return self.TYPE_CHOICES[self.vehicle_type][1]

    @property
    def missing_requirements(self):
        missing_str = ''

        if self.manager is None:
            missing_str += 'manager'

        if self.vehicle is None:
            if missing_str != '':
                missing_str += ', '
            missing_str += 'vehicle'

        if self.driver is None:
            if missing_str != '':
                missing_str += ', '
            missing_str += 'driver'

        if self.key_color is None:
            if missing_str != '':
                missing_str += ', '
            missing_str += 'key-tag color'

        if self.card_num is None:
            if missing_str != '':
                missing_str += ', '
            missing_str += 'card #'

        if self.status == 7 or self.status == 2:

transportation/templates/transportation/budget-form.html
{% extends "transportation/base.html" %}

{% load static %}

{% block content %}
{% load i18n %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load django_tables2 %}
<div class="container">
  <div class="jumbotron">
    <h1>{{ pagetitle }}</h1>
    <p>Please fill out all the required fields.</p>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <form id="budget-form" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button id="budget-submit-button" type="submit" name="submit" class="btn btn-primary">
                Submit
            </button>
            <button id="budget-cancel-button" type="cancel" name="cancel" class="btn btn-danger">
                Cancel
            </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

transportation/templates/transportation/department-form.html
{% extends "transportation/base.html" %}

{% load static %}

{% block content %}
{% load i18n %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load django_tables2 %}
<div class="container">
  <div class="jumbotron">
    <h1>{{ pagetitle }}</h1>
    <p>Please fill out all the required fields.</p>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <form id="department-form" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button id="department-submit-button" type="submit" name="submit" class="btn btn-primary">
                Submit
            </button>
            <button id="department-cancel-button" type="cancel" name="cancel" class="btn btn-danger">
                Cancel
            </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

transportation/templates/transportation/print-tickets.html
<html>
<head>
<title>Vehicle Request</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
	body {
		margin: 0px;
		font: 8pt sans-serif;
	}
	
	p, input {
		font: 8pt sans-serif;
		margin: 1px;
	}
	td {
		font: 8pt sans-serif;
	}
	div {
	margin: 0px;
	}
</style>
</head>
<body>
{% for triprequest in triprequests %}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><strong>Request No.:</strong> {{ triprequest.pk }}</td>
	
    <td><div align="right"><strong>Date Received:</strong> {{ triprequest.submitted }}</div></td>
  </tr>
</table>

<h3 align="center" style="margin: 0px">Vehicle Request Form</h3>
  <table width="100%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#000000">
    <tr valign="top"> 
      <td width="50%"><p><strong>Requestor Name:</strong>  {{ triprequest.requestor_fullname }}</p></td>
      <td><strong>Department:</strong> {{ triprequest.department }}</td>
    </tr>
    <tr valign="top"> 
      <td><p><strong>Contact Phone:</strong>   {{ triprequest.contact_phone }}
        </p></td>
      <td><strong>Budget Number:</strong>   {{ triprequest.budget }}</td>
    </tr>
    <tr valign="top"> 
      <td><p><strong>Email:</strong>   {{ triprequest.contact_email }}</p></td>
      <td><p><strong>Destination:</strong>   {{ triprequest.destination }}</p></td>
    </tr>
    <tr valign="top"> 
      <td><p><strong>Departure</strong>
          <strong>Date/Time:</strong> {{ triprequest.depart_est }}
      <td><p><strong>Return</strong> 
          <strong>Date/Time:</strong> {{ triprequest.return_est }}
    </tr>
    <tr valign="top"> 
      <td><p><strong>Driver:</strong>   {{ triprequest.driver_fullname }}</p></td>
      <td><strong>Vehicle Type:</strong>   {{ triprequest.get_vehicle_type_display }} w/ Trailer: {% if triprequest.trailer %}Yes{% else %}No{% endif %}</td>
    </tr>
    <tr valign="top"> 
      <td><strong>Number in Party:</strong>   {{ triprequest.party_count }}
      </td>
      <td><strong>Approximate Mileage:</strong>   {{ triprequest.mileage_est }}
    </tr> 
<table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td><p><strong>Purpose:</strong>
        <p>{{ triprequest.purpose }}
      </td></tr>
<tr valign="top"><td>
	<div align="center"><p><strong><font size="2">Conditions</font></strong></p></div>
    <p align="justify">
		1. Under no circumstance is any ministry-owned, leased, or rented vehicle to be used for personal use.<br>
		2. Must be an approved driver on our insurance policy.<br>
        3. Must be 21 years of age.<br>
        4. Must have a valid Virginia driver's license with the proper class and endorsements for the type of vehicle used.<br>
        5. In the event of an accident or a breakdown of the vehicle you are driving, please <b>contact the Security Office at (434) 582-7605 or (434) 582-7641</b>. Please leave your name, the group you are with, your exact location, and the phone number where you can be reached. Security will contact the Transportation employee on call at that time.  Furthermore, the driver must go to the Transportation Office to fill out an accident form within 24 hours. Accidents occurring on a weekend must be reported on Monday.<br>
        6. All vehicles, when returned, must have all windows and doors closed.<br>
        7. All vehicles must be clean inside when returned.<br>
        8. Return all keys, this form, and maintenance request form (if necessary) to the Bus Office. Return all vehicles to the same area that you picked them up from unless instructed otherwise.<br>
        9. If you were given a gas card, it must be returned to the office where you received it with all gas receipts.<br>
     </p>
</td>
	    </tr>
	  </table>
  </table>
<table width="100%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#000000">
  <tr> 
      <td colspan="2"><strong>Approval <em>( {{ triprequest.get_status_display }} )</em></strong></td>
      <td width="157"><strong>Date</strong></td>
  </tr>
  <tr valign="top"> 
    <td colspan="2">Originator:   {{ triprequest.requestor_fullname }}<p>&nbsp;</td>
    <td>  {{ triprequest.submitted }}</td>
  </tr>
  <tr valign="top"> 
      <td colspan="2">Transportation Office:   {{ triprequest.manager_fullname }}<p>&nbsp;
      <td>{{ triprequest.updated }}</td>
  </tr>
  <tr valign="top"> 
      <td width="355"><strong>Vehicle #</strong>   {{ triprequest.vehicle.num }}<p>&nbsp;</td>
	  <td width="208"><strong>Key Color</strong>   {{ triprequest.key_color }}</td>  
	  <td><strong>Gas Card #</strong>   {{ triprequest.card_num }}</td>
  </tr>
</table>
<br>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td><div align="center"><strong><font size="2">Driver Report </font></strong></div></td>
  </tr>
  <tr> 
    <td><strong>To be completed upon vehicle departure and return:</strong></td>
  </tr>
</table>  
<table width="98%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#000000">  
  <tr valign="top"> 
      <td>Departure Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )</i><p>&nbsp;
      </td>
      <td>Beginning Mileage:   </td>
  </tr>
  <tr valign="top"> 
      <td>Return Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )</i><p>&nbsp;</td>
      <td>Ending Mileage:   </td>
  </tr>
  <tr valign="top"> 
      <td>Fuel Cost:<p>&nbsp;</p></td>
      <td>Total Mileage:   </td>
  </tr>
  </table>
<p></p><strong>Upon Return:</strong>
<br>Is the inside of the vehicle clean? <input name="vehicle_clean" type="checkbox" id="vehicle_clean" value="1">
<br>Can the vehicle be driven forward from this parking space? <input name="vehicle_backedin" type="checkbox" id="vehicle_backedin" value="1">
<p>Write any vehicle problems below:
<table width="100%" height="100px" border="1">
<tr><td></td></tr>
</table>
<p>&nbsp;</p><br/><br/>
<p>Driver's Name (Print): _____________________________________________________________</p><br/><br/><br/>
<p>Driver's Signature: _______________________________________________________________</p><br/><br/><br/>
<div style='page-break-after:always'></div>
{% endfor %}
<table width="100%" border="1" cellspacing="1" cellpadding="0">
  <tr> 
    <td colspan="5"><strong>Vehicle Request Statistical Ticket Summary</strong></td>
	<td align="right"><strong>Printed on {% now "SHORT_DATETIME_FORMAT" %}</strong></td>
  </tr>
  <tr> 
    <th width="8%">ID</th>
    <th width="19%">ORIGINATOR</th>
    <th width="16%">DEPART<br>
      DATE</th>
    <th width="15%">RETURN<br>DATE</th>
    <th width="22%">DRIVER</th>
    <th width="20%">VEHICLE</th>
  </tr>
    {% for triprequest in triprequests %}
    <tr>
        <td>{{ triprequest.pk }}</td>
        <td>{{ triprequest.contact_fullname }}</td>
        <td>{{ triprequest.depart_est }}</td>
        <td>{{ triprequest.return_est }}</td>
        <td>{{ triprequest.driver_fullname }}</td>
        <td>{{ triprequest.vehicle }} w/ trailer: {{ triprequest.trailer }}</td>
    </tr>
    {% endfor %}
</table>
<p>&nbsp;</p>
</body>
</html>